name = "gh-tik-tak-toe"
type = "javascript"

account_id = "653c02f69b43aa8be5f4ace7cac02dbd"
workers_dev = true
route = ""
zone_id = "b233e1c4e0316e1921defdd2d3ca870b"
compatibility_date = "2021-10-19"

format = "modules"
main = "./index.js"

kv_namespaces = [
  { binding = "GAMESTORE", id = "5f357758b8a34089970a6601ad37457d", preview_id = "68013baf037b43c1a83d09d638ada1f4" }
]